name: Action - Push develop

on:
  push:
    branches:
      - develop

jobs:

  build_and_push:
    uses: ./.github/workflows/build-and-push.yml
    secrets:
      HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
      HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}

  deploy_staging:
    needs: [build_and_push]
    uses: ./.github/workflows/deploy-staging.yml
    secrets:
      PORTAINER_HOOK_FRONTEND: ${{ secrets.PORTAINER_HOOK_FRONTEND }}
