name: Job - Lint and test

on:
  workflow_call:

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    env:
      CI: ""
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.12.1
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
      - run: |
          yarn
          yarn build
          yarn lint
          yarn test
